name: dart_samples
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  postgres: ^3.4.0
  mongo_dart: ^0.10.3
  intl: ^0.19.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
